version: 2.1
jobs:
  armorcode-validate:
    docker:
      - image: byrnedo/alpine-curl
    environment:
      product: Niki
      subProduct: n1
      environment: Production
      token: $token
      buildTool: CIRCLE_CI
      buildNumber: "<< pipeline.number >>"
    steps:
      - run:
          name: "Armorcode Validate"
          command: |
              wget https://qa.armorcode.ai/static/scripts/slastatus.sh
              sh slastatus.sh
workflows:
  armorcode-validation-workflow:
    jobs:
      - armorcode-validate
